#!/usr/bin/groovy
@Library('groot@1.0')
def version = determineVersion();

node {
    genericPipeline(
    	version: version, 
    	build: {
	        buildImageViaRemote(projectName:getProjectName(),
          version:version,
          files:"*");
    	})
}
